name: f72
url: http://https://f72.github.io
description: &c

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: rouge
paginate: 20

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
